version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var