server:
    port: 8082

spring:
    application:
        name: MS-Email
    datasource:
        url: jdbc:postgresql://localhost:5432/ms-email
        username: root
        password: toor
    jpa:
        hibernate:
            ddl-auto: update