server:
    port: 8082

spring:
    application:
        name: MS-Email
    datasource:
        url: jdbc:postgresql://localhost:5432/ms-email
        username: root
        password: toor
    jpa:
        hibernate:
            ddl-auto: update
    rabbitmq:
        addresses: **setAddress**
    mail:
        host: sandbox.smtp.mailtrap.io
        port: 587
        username: **setUsername**
        password: **setPassword**
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

broker:
    queue:
        email:
            name: default.email