server:
    port: 8081

spring:
    application:
        name: MS-User
    datasource:
        url: jdbc:postgresql://localhost:5432/ms-user
        username: root
        password: toor
    jpa:
        hibernate:
            ddl-auto: update