server:
    port: 8081

spring:
    application:
        name: MS-User
    datasource:
        url: jdbc:postgresql://localhost:5432/ms-user
        username: root
        password: toor
    jpa:
        hibernate:
            ddl-auto: update
    rabbitmq:
        addresses: amqps://ttkzwpdg:b7myp5odzkn38x9D1rNSqlavKePi2FoR@fish.rmq.cloudamqp.com/ttkzwpdg

broker:
    queue:
        email:
            name: default.email